### ISSUE TITLE
Альтернативный формат вывода

### ISSUE THREAD

**Issue by the-vindicar** [phoenix-mstu/net_list_minimizer#2]
Некоторым утилитам (типа OpenVPN) удобнее работать с подсетью в записи `1.2.3.4 255.255.255.0`, а не `1.2.3.4\24`.
Имеет ли смысл добавить такой формат вывода в скрипт?

Если что, могу предоставить пуллреквест, но там будет несколько больше изменений.

**Comment by phoenix-mstu** [comment]
Ничего против не имею, только желательно прикрыть это флагом. Например --print-mask
